// Generated by https://quicktype.io

export interface AuthyVerifyOtpResponseInterface {
  message: string;
  token: string;
  success: string;
  device: Device;
}

export interface Device {
  city: string;
  country: string;
  ip: string;
  region: string;
  registration_city: string;
  registration_country: string;
  registration_device_id: number;
  registration_ip: string;
  registration_method: string;
  registration_region: string;
  os_type: string;
  last_account_recovery_at: null;
  id: number;
  registration_date: number;
}
